package de.rolfwalker.flightbuddy.core.domain

data class AirlineInfo(val iata: String, val icao: String, val name: String)

/** ICAO/IATA → name for viewport traffic logos. OpenSky callsigns are usually ICAO (`DLH441`). */
object AirlineCatalog {
    private val rows = listOf(
        AirlineInfo("LH", "DLH", "Lufthansa"),
        AirlineInfo("EW", "EWG", "Eurowings"),
        AirlineInfo("4Y", "OCN", "Discover Airlines"),
        AirlineInfo("DE", "CFG", "Condor"),
        AirlineInfo("X3", "TUI", "TUI fly"),
        AirlineInfo("AF", "AFR", "Air France"),
        AirlineInfo("A5", "HOP", "Air France Hop"),
        AirlineInfo("BA", "BAW", "British Airways"),
        AirlineInfo("U2", "EZY", "easyJet"),
        AirlineInfo("U2", "EJU", "easyJet Europe"),
        AirlineInfo("LS", "EXS", "Jet2"),
        AirlineInfo("VS", "VIR", "Virgin Atlantic"),
        AirlineInfo("EI", "EIN", "Aer Lingus"),
        AirlineInfo("FR", "RYR", "Ryanair"),
        AirlineInfo("RK", "RUK", "Ryanair UK"),
        AirlineInfo("W6", "WZZ", "Wizz Air"),
        AirlineInfo("W4", "WMT", "Wizz Air Malta"),
        AirlineInfo("W9", "WUK", "Wizz Air UK"),
        AirlineInfo("KL", "KLM", "KLM"),
        AirlineInfo("HV", "TRA", "Transavia"),
        AirlineInfo("TO", "TVF", "Transavia France"),
        AirlineInfo("LX", "SWR", "SWISS"),
        AirlineInfo("WK", "EDW", "Edelweiss"),
        AirlineInfo("OS", "AUA", "Austrian Airlines"),
        AirlineInfo("SN", "BEL", "Brussels Airlines"),
        AirlineInfo("LG", "LGL", "Luxair"),
        AirlineInfo("IB", "IBE", "Iberia"),
        AirlineInfo("I2", "IBS", "Iberia Express"),
        AirlineInfo("VY", "VLG", "Vueling"),
        AirlineInfo("UX", "AEA", "Air Europa"),
        AirlineInfo("TP", "TAP", "TAP Air Portugal"),
        AirlineInfo("AZ", "ITY", "ITA Airways"),
        AirlineInfo("AZ", "AZA", "ITA Airways"),
        AirlineInfo("EN", "DLA", "Air Dolomiti"),
        AirlineInfo("AY", "FIN", "Finnair"),
        AirlineInfo("SK", "SAS", "SAS"),
        AirlineInfo("DY", "NAX", "Norwegian"),
        AirlineInfo("D8", "NSZ", "Norwegian"),
        AirlineInfo("WF", "WIF", "Widerøe"),
        AirlineInfo("FI", "ICE", "Icelandair"),
        AirlineInfo("OG", "FPY", "PLAY"),
        AirlineInfo("BT", "BTI", "airBaltic"),
        AirlineInfo("LO", "LOT", "LOT Polish Airlines"),
        AirlineInfo("OK", "CSA", "Czech Airlines"),
        AirlineInfo("QS", "TVS", "Smartwings"),
        AirlineInfo("OU", "CTN", "Croatia Airlines"),
        AirlineInfo("JU", "ASL", "Air Serbia"),
        AirlineInfo("RO", "ROT", "TAROM"),
        AirlineInfo("FB", "LZB", "Bulgaria Air"),
        AirlineInfo("A3", "AEE", "Aegean"),
        AirlineInfo("GQ", "SEH", "SKY express"),
        AirlineInfo("OA", "OAL", "Olympic Air"),
        AirlineInfo("TK", "THY", "Turkish Airlines"),
        AirlineInfo("PC", "PGT", "Pegasus"),
        AirlineInfo("XQ", "SXS", "SunExpress"),
        AirlineInfo("VF", "TKJ", "AJet"),
        AirlineInfo("EK", "UAE", "Emirates"),
        AirlineInfo("QR", "QTR", "Qatar Airways"),
        AirlineInfo("EY", "ETD", "Etihad Airways"),
        AirlineInfo("GF", "GFA", "Gulf Air"),
        AirlineInfo("WY", "OMA", "Oman Air"),
        AirlineInfo("SV", "SVA", "Saudia"),
        AirlineInfo("MS", "MSR", "Egyptair"),
        AirlineInfo("AT", "RAM", "Royal Air Maroc"),
        AirlineInfo("TU", "TAR", "Tunisair"),
        AirlineInfo("ET", "ETH", "Ethiopian Airlines"),
        AirlineInfo("KQ", "KQA", "Kenya Airways"),
        AirlineInfo("SA", "SAA", "South African Airways"),
        AirlineInfo("SQ", "SIA", "Singapore Airlines"),
        AirlineInfo("CX", "CPA", "Cathay Pacific"),
        AirlineInfo("NH", "ANA", "All Nippon Airways"),
        AirlineInfo("JL", "JAL", "Japan Airlines"),
        AirlineInfo("KE", "KAL", "Korean Air"),
        AirlineInfo("OZ", "AAR", "Asiana"),
        AirlineInfo("CA", "CCA", "Air China"),
        AirlineInfo("MU", "CES", "China Eastern"),
        AirlineInfo("CZ", "CSN", "China Southern"),
        AirlineInfo("CI", "CAL", "China Airlines"),
        AirlineInfo("BR", "EVA", "EVA Air"),
        AirlineInfo("TG", "THA", "THAI"),
        AirlineInfo("VN", "HVN", "Vietnam Airlines"),
        AirlineInfo("MH", "MAS", "Malaysia Airlines"),
        AirlineInfo("GA", "GIA", "Garuda Indonesia"),
        AirlineInfo("QF", "QFA", "Qantas"),
        AirlineInfo("JQ", "JST", "Jetstar"),
        AirlineInfo("NZ", "ANZ", "Air New Zealand"),
        AirlineInfo("AI", "AIC", "Air India"),
        AirlineInfo("6E", "IGO", "IndiGo"),
        AirlineInfo("UK", "VTI", "Vistara"),
        AirlineInfo("AA", "AAL", "American Airlines"),
        AirlineInfo("DL", "DAL", "Delta Air Lines"),
        AirlineInfo("UA", "UAL", "United Airlines"),
        AirlineInfo("WN", "SWA", "Southwest Airlines"),
        AirlineInfo("B6", "JBU", "JetBlue"),
        AirlineInfo("AS", "ASA", "Alaska Airlines"),
        AirlineInfo("NK", "NKS", "Spirit"),
        AirlineInfo("F9", "FFT", "Frontier"),
        AirlineInfo("AC", "ACA", "Air Canada"),
        AirlineInfo("WS", "WJA", "WestJet"),
        AirlineInfo("AM", "AMX", "Aeroméxico"),
        AirlineInfo("LA", "LAN", "LATAM"),
        AirlineInfo("AV", "AVA", "Avianca"),
        AirlineInfo("G3", "GLO", "GOL"),
        AirlineInfo("AD", "AZU", "Azul"),
        AirlineInfo("AR", "ARG", "Aerolíneas Argentinas"),
        AirlineInfo("LY", "ELY", "El Al"),
        AirlineInfo("LY", "LLM", "El Al"),
        AirlineInfo("RJ", "RJA", "Royal Jordanian"),
        AirlineInfo("ME", "MEA", "Middle East Airlines"),
        AirlineInfo("IR", "IRA", "Iran Air"),
        AirlineInfo("PK", "PIA", "PIA"),
        AirlineInfo("UL", "ALK", "SriLankan"),
        AirlineInfo("BG", "BBC", "Biman Bangladesh"),
        AirlineInfo("PR", "PAL", "Philippine Airlines"),
        AirlineInfo("5J", "CEB", "Cebu Pacific"),
        AirlineInfo("AK", "AXM", "AirAsia"),
        AirlineInfo("D7", "XAX", "AirAsia X"),
        AirlineInfo("TR", "TGW", "Scoot"),
        AirlineInfo("OD", "MXD", "Malindo"),
        AirlineInfo("HO", "DKH", "Juneyao Air"),
        AirlineInfo("9C", "CQH", "Spring Airlines"),
        AirlineInfo("HU", "CHH", "Hainan Airlines"),
        AirlineInfo("MF", "CXA", "XiamenAir"),
        AirlineInfo("ZH", "CSZ", "Shenzhen Airlines"),
        AirlineInfo("SC", "CDG", "Shandong Airlines"),
        AirlineInfo("FM", "CSH", "Shanghai Airlines"),
        AirlineInfo("3U", "CSC", "Sichuan Airlines"),
        AirlineInfo("JD", "CBJ", "Capital Airlines"),
        AirlineInfo("TV", "TBA", "Tibet Airlines"),
        AirlineInfo("Y8", "YZR", "Suparna"),
        AirlineInfo("KE", "KAL", "Korean Air"),
        AirlineInfo("LJ", "JNA", "Jin Air"),
        AirlineInfo("TW", "TWB", "T'way Air"),
        AirlineInfo("7C", "JJA", "Jeju Air"),
        AirlineInfo("ZE", "ESR", "Eastar Jet"),
        AirlineInfo("MM", "APJ", "Peach"),
        AirlineInfo("GK", "JJP", "Jetstar Japan"),
        AirlineInfo("BC", "SKY", "Skymark"),
        AirlineInfo("HD", "ADO", "Air Do"),
        AirlineInfo("NU", "JTA", "Japan Transocean"),
        AirlineInfo("HA", "HAL", "Hawaiian Airlines"),
        AirlineInfo("SY", "SCX", "Sun Country"),
        AirlineInfo("MX", "MXA", "Breeze"),
        AirlineInfo("XP", "CXP", "Avelo"),
        AirlineInfo("PD", "POE", "Porter"),
        AirlineInfo("TS", "TSC", "Air Transat"),
        AirlineInfo("4O", "AIJ", "Interjet"),
        AirlineInfo("VB", "VIV", "VivaAerobus"),
        AirlineInfo("Y4", "VOI", "Volaris"),
        AirlineInfo("CM", "CMP", "Copa Airlines"),
        AirlineInfo("TA", "TAI", "TACA"),
        AirlineInfo("H2", "SKU", "SKY Airline"),
        AirlineInfo("JA", "JAT", "JetSMART"),
        AirlineInfo("4C", "ARE", "LATAM Colombia"),
        AirlineInfo("LP", "LPE", "LATAM Peru"),
        AirlineInfo("JJ", "TAM", "LATAM Brasil"),
        AirlineInfo("PZ", "LAP", "LATAM Paraguay"),
        AirlineInfo("UC", "LCO", "LATAM Cargo"),
        AirlineInfo("IB", "IBS", "Iberia Express"),
        AirlineInfo("V7", "VOE", "Volotea"),
        AirlineInfo("NT", "IBB", "Binter Canarias"),
        AirlineInfo("I2", "IBS", "Iberia Express"),
        AirlineInfo("UX", "AEA", "Air Europa"),
        AirlineInfo("YW", "ANE", "Air Nostrum"),
        AirlineInfo("NI", "PGA", "Portugália"),
        AirlineInfo("S4", "RZO", "SATA"),
        AirlineInfo("SP", "SAT", "SATA Air Açores"),
        AirlineInfo("A2", "AZI", "Astra Airlines"),
        AirlineInfo("XM", "JTG", "Jazeera Airways"),
        AirlineInfo("J9", "JZR", "Jazeera Airways"),
        AirlineInfo("XY", "KNE", "flynas"),
        AirlineInfo("F3", "FAD", "flyadeal"),
        AirlineInfo("G9", "ABY", "Air Arabia"),
        AirlineInfo("3L", "ADY", "Air Arabia Abu Dhabi"),
        AirlineInfo("FZ", "FDB", "flydubai"),
        AirlineInfo("KK", "KKK", "AtlasGlobal"),
        AirlineInfo("XQ", "SXS", "SunExpress"),
        AirlineInfo("XC", "CAI", "Corendon"),
        AirlineInfo("6H", "ISR", "Israir"),
        AirlineInfo("IZ", "AIZ", "Arkia"),
        AirlineInfo("A4", "AEF", "Azimuth"),
        AirlineInfo("SU", "AFL", "Aeroflot"),
        AirlineInfo("S7", "SBI", "S7 Airlines"),
        AirlineInfo("U6", "SVR", "Ural Airlines"),
        AirlineInfo("DP", "PBD", "Pobeda"),
        AirlineInfo("FV", "SDM", "Rossiya"),
        AirlineInfo("N4", "NWS", "Nordwind"),
        AirlineInfo("UT", "UTA", "UTair"),
        AirlineInfo("B2", "BRU", "Belavia"),
        AirlineInfo("PS", "AUI", "Ukraine International"),
        AirlineInfo("7W", "WRC", "Windrose"),
        AirlineInfo("5F", "FIA", "FlyOne"),
        AirlineInfo("H4", "LTC", "HiSky"),
        AirlineInfo("W9", "WUK", "Wizz Air UK"),
        AirlineInfo("RR", "RYS", "Buzz"),
        AirlineInfo("FR", "RYS", "Buzz"),
        AirlineInfo("RK", "RUK", "Ryanair UK"),
        AirlineInfo("LS", "EXS", "Jet2"),
        AirlineInfo("BY", "TOM", "TUI Airways"),
        AirlineInfo("OR", "TFL", "TUI fly Netherlands"),
        AirlineInfo("TB", "JAF", "TUI fly Belgium"),
        AirlineInfo("X3", "TUI", "TUI fly"),
        AirlineInfo("6B", "BLX", "TUIfly Nordic"),
        AirlineInfo("ST", "GMI", "Germania"),
        AirlineInfo("HF", "LFO", "Air Côte d'Ivoire"),
        AirlineInfo("AT", "RAM", "Royal Air Maroc"),
        AirlineInfo("DT", "DTA", "TAAG"),
        AirlineInfo("KP", "SKK", "ASKY"),
        AirlineInfo("WB", "RWD", "RwandAir"),
        AirlineInfo("TC", "ATC", "Air Tanzania"),
        AirlineInfo("TM", "LAM", "LAM Mozambique"),
        AirlineInfo("FN", "FNX", "Fastjet"),
        AirlineInfo("P0", "PFZ", "Proflight Zambia"),
        AirlineInfo("MK", "MAU", "Air Mauritius"),
        AirlineInfo("UU", "REU", "Air Austral"),
        AirlineInfo("SS", "CRL", "Corsair"),
        AirlineInfo("TX", "FWI", "Air Caraïbes"),
        AirlineInfo("BF", "FPO", "French Bee"),
        AirlineInfo("XK", "CCM", "Air Corsica"),
        AirlineInfo("AF", "AFR", "Air France"),
        AirlineInfo("A5", "HOP", "Air France Hop"),
        AirlineInfo("V7", "VOE", "Volotea"),
        AirlineInfo("U2", "EZY", "easyJet"),
        AirlineInfo("DS", "EZS", "easyJet Switzerland"),
        AirlineInfo("EC", "EJU", "easyJet Europe"),
        AirlineInfo("EJU", "EJU", "easyJet Europe"),
        AirlineInfo("VL", "MHV", "Med-View"),
        AirlineInfo("IQ", "QFA", "QantasLink"),
        AirlineInfo("QF", "QFA", "Qantas"),
        AirlineInfo("VA", "VOZ", "Virgin Australia"),
        AirlineInfo("JQ", "JST", "Jetstar"),
        AirlineInfo("TT", "TAS", "Tigerair Australia"),
        AirlineInfo("NZ", "ANZ", "Air New Zealand"),
        AirlineInfo("DJ", "AWQ", "AirAsia Japan"),
        AirlineInfo("ID", "BTK", "Batik Air"),
        AirlineInfo("QG", "CTV", "Citilink"),
        AirlineInfo("JT", "LNI", "Lion Air"),
        AirlineInfo("IW", "WON", "Wings Air"),
        AirlineInfo("QZ", "AWQ", "Indonesia AirAsia"),
        AirlineInfo("FD", "AIQ", "Thai AirAsia"),
        AirlineInfo("XJ", "TAX", "Thai AirAsia X"),
        AirlineInfo("Z2", "APG", "Philippines AirAsia"),
        AirlineInfo("AK", "AXM", "AirAsia"),
        AirlineInfo("D7", "XAX", "AirAsia X"),
        AirlineInfo("XT", "IDX", "Indonesia AirAsia X"),
        AirlineInfo("I5", "IAD", "AirAsia India"),
        AirlineInfo("KT", "KIL", "AirAsia Cambodia"),
        AirlineInfo("Z9", "MYM", "Myanmar Airways"),
        AirlineInfo("8M", "MMA", "Myanmar Airways International"),
        AirlineInfo("PG", "BKP", "Bangkok Airways"),
        AirlineInfo("SL", "TLM", "Thai Lion Air"),
        AirlineInfo("VZ", "TVJ", "Thai Vietjet"),
        AirlineInfo("VJ", "VJC", "VietJet Air"),
        AirlineInfo("BL", "BVN", "Pacific Airlines"),
        AirlineInfo("QH", "BAV", "Bamboo Airways"),
        AirlineInfo("NX", "AQA", "Air Macau"),
        AirlineInfo("UO", "HKE", "HK Express"),
        AirlineInfo("HX", "CRK", "Hong Kong Airlines"),
        AirlineInfo("CX", "CPA", "Cathay Pacific"),
        AirlineInfo("KA", "HDA", "Cathay Dragon"),
        AirlineInfo("CI", "CAL", "China Airlines"),
        AirlineInfo("BR", "EVA", "EVA Air"),
        AirlineInfo("IT", "TTW", "Tigerair Taiwan"),
        AirlineInfo("B7", "UIA", "UNI Air"),
        AirlineInfo("AE", "MDA", "Mandarin Airlines"),
        AirlineInfo("JX", "SJX", "STARLUX"),
        AirlineInfo("MM", "APJ", "Peach"),
        AirlineInfo("GK", "JJP", "Jetstar Japan"),
        AirlineInfo("JW", "VNL", "Vanilla Air"),
        AirlineInfo("7G", "SFJ", "StarFlyer"),
        AirlineInfo("BC", "SKY", "Skymark"),
        AirlineInfo("NH", "ANA", "All Nippon Airways"),
        AirlineInfo("JL", "JAL", "Japan Airlines"),
        AirlineInfo("NQ", "NJA", "Air Japan"),
        AirlineInfo("6J", "SNJ", "Solaseed Air"),
        AirlineInfo("HD", "ADO", "Air Do"),
        AirlineInfo("FW", "IBX", "Ibex Airlines"),
        AirlineInfo("OC", "ANW", "Oriental Air Bridge"),
        AirlineInfo("JC", "JAL", "J-Air"),
        AirlineInfo("NU", "JTA", "Japan Transocean Air"),
        AirlineInfo("OH", "COM", "PSA Airlines"),
        AirlineInfo("YX", "RPA", "Republic Airways"),
        AirlineInfo("MQ", "ENY", "Envoy Air"),
        AirlineInfo("OO", "SKW", "SkyWest"),
        AirlineInfo("9E", "EDV", "Endeavor Air"),
        AirlineInfo("PT", "PDT", "Piedmont"),
        AirlineInfo("ZW", "AWI", "Air Wisconsin"),
        AirlineInfo("C5", "UCA", "CommutAir"),
        AirlineInfo("G7", "GJS", "GoJet"),
        AirlineInfo("CP", "CPZ", "Compass"),
        AirlineInfo("QX", "QXE", "Horizon Air"),
        AirlineInfo("KS", "PEN", "PenAir"),
        AirlineInfo("AS", "ASA", "Alaska Airlines"),
        AirlineInfo("HA", "HAL", "Hawaiian Airlines"),
        AirlineInfo("F8", "FLE", "Flair"),
        AirlineInfo("WO", "WSW", "Swoop"),
        AirlineInfo("TS", "TSC", "Air Transat"),
        AirlineInfo("PD", "POE", "Porter"),
        AirlineInfo("WG", "SWG", "Sunwing"),
        AirlineInfo("4N", "ANT", "Air North"),
        AirlineInfo("5T", "AKT", "Canadian North"),
        AirlineInfo("7F", "FAB", "First Air"),
        AirlineInfo("MO", "CAW", "Calm Air"),
        AirlineInfo("JV", "BLS", "Bearskin"),
        AirlineInfo("QK", "JZA", "Jazz"),
        AirlineInfo("RV", "ROU", "Air Canada Rouge"),
        AirlineInfo("AC", "ACA", "Air Canada"),
        AirlineInfo("WS", "WJA", "WestJet"),
        AirlineInfo("WR", "WEN", "WestJet Encore"),
    )

    private val byIcao = HashMap<String, AirlineInfo>(rows.size).apply {
        for (row in rows) putIfAbsent(row.icao, row)
    }
    private val byIata = HashMap<String, AirlineInfo>(rows.size).apply {
        for (row in rows) putIfAbsent(row.iata, row)
    }

    fun lookup(prefix: String): AirlineInfo? {
        val key = prefix.trim().uppercase()
        if (key.isEmpty()) return null
        return byIcao[key] ?: byIata[key]
    }
}
